server:
  port: 6310

# Logging Settings
logging:
  level:
    '[cn.lhfei.camel]': debug
    '[org.springframework]': info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 1024000

# for Camel test
greeting: Hefei Li
timer:
  period: 2000

springdoc:
  api-docs:
    enabled: true
    path: "/endpoints"
  packages-to-scan:
    - cn.lhfei.camel.web.api
  swagger-ui:
    path: /docs/index.html