server:
  port: 8800

rstream:
  basic:
    camel-to-reactor: true
    reactor-to-camel: true
    camel-to-reactor-in-out: true
    reactor-to-camel-in-out: true
  client-api:
    rest: true
    workflow: true
  others:
    rest: true
